"use client";

import "./styles/globals.css";

// export const metadata = {
//   title: "Web",
//   description: "Generated by LeeDW",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <div>{children}</div>
      </body>
    </html>
  );
}
